apiVersion: v1
kind: Service
metadata:
  name: k8-user-service
spec:
  ports:
    - name: 80-8083
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app: k8-user-service
  type: LoadBalancer
