apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service
spec:
  selector:
    matchLabels:
      app: music-service
  template:
    metadata:
      labels:
        app: music-service
    spec:
      containers:
        - image: yousoundd/music-service:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          name: music-service
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: music-service
  type: ClusterIP
