apiVersion: v1
kind: Service
metadata:
  name: k8-api-gateway
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8-api-gateway
  type: LoadBalancer
