apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-discovery-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-discovery-server
  template:
    metadata:
      labels:
        app: k8-discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761

