apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-music-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-music-service
  template:
    metadata:
      labels:
        app: k8-music-service
    spec:
      containers:
        - name: music-service
          image: music-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081

