apiVersion: v1
kind: Service
metadata:
  name: k8-music-service
spec:
  ports:
    - name: 80-8081
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: k8-music-service
  type: LoadBalancer
