apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-user-service
  template:
    metadata:
      labels:
        app: k8-user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083

