apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: yousoundd/user-service:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          name: user-service
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app: user-service
  type: ClusterIP
