apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-04-07T14:24:07Z"
  generation: 1
  labels:
    app: user-service
  name: user-service
  namespace: default
  resourceVersion: "27858"
  uid: 710b9f37-be72-4f59-9855-bc8f3d2e3139
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
    spec:
      containers:
      - image: yousoundd/user-service:0.0.1
        imagePullPolicy: IfNotPresent
        name: user-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-07T14:24:11Z"
    lastUpdateTime: "2023-04-07T14:24:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-04-07T14:24:07Z"
    lastUpdateTime: "2023-04-07T14:24:11Z"
    message: ReplicaSet "user-service-6f5f7d557f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-04-07T14:24:20Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: user-service
  name: user-service
  namespace: default
  resourceVersion: "28176"
  uid: a0785403-6785-452f-abf8-abb4c611514b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.84.5.153
  clusterIPs:
    - 10.84.5.153
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30425
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: user-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 35.202.38.29
