apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
spec:
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - image: yousoundd/security-service:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          name: security-service
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app: security-service
  type: ClusterIP
