name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Music Service
        run: |
          cd backend/yousound/music-service
          docker build -t yousoundd/music-service:0.0.1 .
          docker push yousoundd/music-service:0.0.1

      - name: Build and Push User Service
        run: |
          cd backend/yousound/user-service
          docker build -t yousoundd/user-service:0.0.1 .
          docker push yousoundd/user-service:0.0.1
