# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-push-docker-image:
    runs-on: ubuntu-latest
    services:
      frontend:
        image: yousoundd/frontend:0.0.1
        ports:
          - "3000:3000"
      security:
        image: yousoundd/security-service:0.0.1
        ports:
          - "8082:8082" 
    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Gradle Clean
        run: | 
          cd backend/yousound
          gradle clean
      - name: Build with Gradle
        run: |
          cd backend/yousound
          gradle build
      - name: Test YouSound
        run: |
          cd backend/yousound
          gradle test
      - name: Install frontend dependencies
        run: |
          cd frontend/yousound-frontend
          yarn
      - name: Build and start the frontend application
        run: |
          cd frontend/yousound-frontend
          yarn build
          yarn start &
      - name: Wait for frontend application to start
        run: |
          sleep 30s
      - name: Build and start the backend application
        run: |
          cd backend/yousound/security-service
          chmod +x gradlew
          ./gradlew build
          java -jar build/libs/security-service-1.0-SNAPSHOT.jar &
      - name: Wait for backend application to start
        run: |
          sleep 30s
      - name: Security scan with OWASP ZAP
        run: |
          docker run --network="host" -t owasp/zap2docker-stable zap-baseline.py -t http://172.17.0.1:3000 -I
          docker run --network="host" -t owasp/zap2docker-stable zap-baseline.py -t http://172.17.0.1:8082 -I
      - name: docker login
        env:
          DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build and Push Discovery Server
        run: |
          cd backend/yousound/discovery-server
          docker build -f Dockerfile . -t yousoundd/discovery-server:0.0.1
          docker push yousoundd/discovery-server:0.0.1
      - name: Build and Push Api Gateway
        run: |
          cd backend/yousound/api-gateway
          docker build -f Dockerfile . -t yousoundd/api-gateway:0.0.1
          docker push yousoundd/api-gateway:0.0.1
      - name: Build and Push Music Service
        run: |
          cd backend/yousound/music-service
          docker build -f Dockerfile . -t yousoundd/music-service:0.0.1
          docker push yousoundd/music-service:0.0.1
      - name: Build and Push Security Service
        run: |
          cd backend/yousound/security-service
          docker build -f Dockerfile . -t yousoundd/security-service:0.0.1
          docker push yousoundd/security-service:0.0.1
      - name: Build and Push Channel Service
        run: |
          cd backend/yousound/social-service
          docker build -f Dockerfile . -t yousoundd/social-service:0.0.1
          docker push yousoundd/social-service:0.0.1
      - name: Build and Push Channel Service
        run: |
          cd backend/yousound/user-service
          docker build -f Dockerfile . -t yousoundd/user-service:0.0.1
          docker push yousoundd/user-service:0.0.1
      - name: Build and Push Frontend
        run: |
          cd frontend/yousound-frontend
          docker build -f Dockerfile . -t yousoundd/frontend:0.0.1
          docker push yousoundd/frontend:0.0.1