# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
      - name: Set working directory
        run: echo "::set-output name=dir::$(find . -type d -name '*-service*' -print -quit)"
        id: set_dir
      - name: Gradle Clean
        run: | 
          cd backend/yousound
          gradle clean
      - name: Build with Gradle
        run: |
          cd ..
          gradle build
        working-directory: ${{steps.set_dir.outputs.dir}}
      - name: Test YouSound
        run: |
          ls
          cd backend/yousound
          gradle test
      - name: docker loginZ
        env:
          DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build and Push Music Service
        run: |
          cd backend/yousound/music-service
          docker build -f Dockerfile . -t yousoundd/music-service:0.0.1
          docker push yousoundd/music-service:0.0.1
      - name: Build and Push User Service
        run: |
          cd backend/yousound/user-service
          docker build -f Dockerfile . -t yousoundd/user-service:0.0.1
          docker push yousoundd/user-service:0.0.1
