# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Set working directory
      run: echo "::set-output name=dir::$(find . -type d -name '*-service*' -print -quit)"
      id: set_dir

    - name: Build with Gradle
      run: gradle build
      working-directory: ${{steps.set_dir.outputs.dir}}
  
  build-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Music Service
        run: |
          cd backend/yousound/music-service
          docker build -t yousoundd/music-service:0.0.1 .
          docker push yousoundd/music-service:0.0.1

      - name: Build and Push User Service
        run: |
          cd backend/yousound/user-service
          docker build -t yousoundd/user-service:0.0.1 .
          docker push yousoundd/user-service:0.0.1