name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Test Music Service
        run: |
          cd yousound/music-service
          gradle test

      - name: Test User Service
        run: |
          cd yousound/user-service
          gradle test
